### ISSUE TITLE
Incluir mas discursos

### ISSUE THREAD

**Issue by luisesanmartin** [ccsuehara/Peruvian-presidents-speeches#1]
Incluir:
- [x] Toma de mando de Paniagua
- [x] Toma de mando de Sagasti
- [x] Discurso de Vizcarra de 2018
- [x] ~~Discurso de Vizcarra de 2020~~ (no incluido porque no es inaugural.
- [ ] Discurso de Castillo de 2021 (cuando este disponible)

Eliminar:
- [x] Discursos anteriores a 1963, primer gobierno de Belaunde

Tambien:
- [x] Convertir notebook en un script de Python y pasar nb a carpeta `Archive`
- [x] Hacer un pkl de solo mensajes inaugurales.

Los discursos se descargan con [este nb](https://github.com/ccsuehara/Peruvian-presidents-speeches/blob/master/notebooks/data_preparation/1_downloading%20Peru%20presidential%20speeches%201956-2019.ipynb), ahi es donde hay que hacer los cambios

**Comment by ccsuehara** [comment]
@luisesanmartin hazle push a mi rama con la modificacion de 1_download_data y 2_data_preparation de carpeta data_preparation

**Comment by luisesanmartin** [comment]
cual es la rama?

**Comment by luisesanmartin** [comment]
ahh ya la vi: develo_pes

**Comment by luisesanmartin** [comment]
queda pendiente incluir el discurso de Castillo cuando este disponible
